version: '3.8'

services:
  app:
    build:
      context: . # Đường dẫn tới Dockerfile (nằm trong thư mục hiện tại)
      dockerfile: Dockerfile
    ports:
      - "8181:8181" # Map cổng 8181 của container ra cổng 8181 của máy host
    volumes:
      - .:/app # Mount thư mục code hiện tại vào /app trong container để tiện phát triển
    environment: # Biến môi trường cho ứng dụng Laravel để kết nối tới PostgreSQL
      DB_CONNECTION: pgsql
      DB_HOST: db # Tên dịch vụ của PostgreSQL trong Docker Compose
      DB_PORT: 5432
      DB_DATABASE: blogy # Thay thế bằng tên database mong muốn
      DB_USERNAME: postgres # Thay thế bằng tên người dùng database
      DB_PASSWORD: postgres # Thay thế bằng mật khẩu database
    depends_on:
      - db # Đảm bảo dịch vụ `db` khởi động trước `app`

  db:
    image: postgres:13 # Sử dụng image PostgreSQL chính thức phiên bản 13
    restart: always # Tự động khởi động lại nếu container bị dừng đột ngột
    environment:
      POSTGRES_DB: blogy # Tên database sẽ được tạo tự động trong container DB
      POSTGRES_USER: postgres # Tên người dùng sẽ được tạo tự động
      POSTGRES_PASSWORD: postgres # Mật khẩu cho người dùng đó
    volumes:
      - db_data:/var/lib/postgresql/data # Mount volume để dữ liệu database được lưu trữ bền vững
      # Tùy chọn: Để copy các script SQL hoặc file .sh vào thư mục khởi tạo DB khi container DB lần đầu được tạo
      # Ví dụ: - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:  
      - "5433:5432"

volumes:
  db_data: # Định nghĩa volume để lưu trữ dữ liệu của PostgreSQL